import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import GeneralLayout from "@/layouts/generalLayout";
import Button from "@/components/atoms/Button/Button";
import LocationSearch from "@/components/filterComponent/LocationSearch";
import CoWorkingSpaceCard from "components/Co-workingSpace/CoWorkingSpaceCard";
import NearbyCard from "components/Co-workingSpace/NearbyCard"
import { coWorkingSpaceData, nearbyCardData } from "@/utils"

const CoWorkingSpace: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralLayout>
          <div className="bg-cover bg-no-repeat bg-[url(../assets/co-workingSpace/targetBg.svg)] pt-[10%] pb-[16%] ">
            <div className="afri-container ">
            <h1 className="xl:text-[48px] md:text-[42px] text-[32px] text-[400] text-white_2 leading-[40px] md:mb-8 mb-4">
                  Target a vibrant community fond of trying new workspaces
                </h1>
            <h5 className="xl:text-[24px] md:text-[16px] text-[14px] text-[400] text-primary_grey xl:leading-[25px] leading-[18px] tracking-[0.16px] xl:w-[40%] w-[55%]">
                  Afrisplash presents workspace providers that are enthusiastic
                  about the african dream with a unique opportunity to sell
                  workspaces.
                </h5>
                <div className="my-14  flex ">
                  <Button
                    type="filled"
                    color="white"
                    text="Continue"
                    classes="w-60 h-12 rounded-[14px] text-sm font-medium capitalize  text-dark_blue bg-white hover:bg-primary_green hover:text-white"
                  />
                </div>
            </div>
          </div>
          <div className="afri-container">
            <div className=" py-14">
              <h1 className="md:text-start text-center text-[40px] text-[700]mb-8">
                Find the perfect space
              </h1>
              <div className="xl:w-[40%] md:w-[45%]">
                <LocationSearch
                  classes="mt-8"
                  placeholder="Choose location"
                  showSelect={false}
                  showFilter={true}
                />
              </div>
            </div>
          </div>
          <div className="afri-container mb-8">
            
              <div className="grid gap-8 md:grid-cols-2">

                {coWorkingSpaceData.map((coWorkingSpace) => (
                  <CoWorkingSpaceCard
                    key={coWorkingSpace.id}
                    name={coWorkingSpace.name}
                    distance={coWorkingSpace.distance}
                    amount={coWorkingSpace.amount}
                    details={coWorkingSpace.details}
                    src={coWorkingSpace.src}
                  />
                ))}
              </div>
          </div>
          <div className="bg-[#FFEDC0] py-14">
            <div className="afri-container mb-5">
              <h1 className="md:text-start text-center text-[40px] text-[700]mb-8">
                Workspaces near you
              </h1>
            </div>
            <div className="afri-container grid gap-8 md:grid-cols-3">
              {nearbyCardData.map((nearbySpace) => (
                <NearbyCard
                  key={nearbySpace.id}
                  name={nearbySpace.name}
                  distance={nearbySpace.distance}
                  amount={nearbySpace.amount}
                  src={nearbySpace.src} />
              ))}
            </div>
          </div>
          <div className="text-center md:p-16 p-5">
            <h1 className="text-[32px] text-[600] leading-[40px] text-dark_blue mb-5">
              Get updated with relevant news from the community
            </h1>
            <h5 className="text-[16px] text-[400] leading-[24px] text-[#667085] mb-14">
              Join over 200 talents and brands already growing with our
              community.
            </h5>
            <div className="grid md:grid-cols-5 grid-cols-3 lg:w-[60%] md:w-[80%]  m-auto mb-14">
              <input
                className="md:col-span-4 col-span-2 block outline-none w-full rounded-l-[8px] border bg-grey-50 py-2 px-3"
                type="text"
                placeholder="Enter your email"
              />
              <Button
                type="filled"
                color="white"
                text="Subscribe"
                classes="  h-12 rounded-r-[8px] text-sm font-medium capitalize  text-white bg-sub_btn"
              />
            </div>
          </div>
      </GeneralLayout>
    </div>
  );
};

export default CoWorkingSpace;
