repository: Afrisplash-Frontend

# you can change the labels to suit your needs if "first-timers-only" is not what you are looking for.
# These are some examples.
labels:
  - first-timers-only
  - help wanted
  - good first issue
  - hacktoberfest
