/* eslint-disable react/no-unescaped-entities */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import GeneralLayout from "layouts/generalLayout";
import styles from "styles/Hire-talent.module.scss";
import AppleLogo from "assets/hire-talent-assets/apple-logo.svg";
import ArrowLeft from "assets/hire-talent-assets/arrow-left.svg";
import BookIllustrator from "assets/hire-talent-assets/book-call-short-dashes-circles.svg";
import BlockQuote from "assets/hire-talent-assets/blockquote-xl.svg";
import CheckBox from "assets/hire-talent-assets/round-bold-check.svg";
import CallIcon from "assets/hire-talent-assets/call_calling.svg";
import EmailIcon from "assets/hire-talent-assets/envelope.svg";
import GoogleLogo from "assets/hire-talent-assets/google-logo.svg";
import HandShakeIcon from "assets/hire-talent-assets/handshake.svg";
import Img1 from "assets/hire-talent-assets/img_1.png";
import Img2 from "assets/hire-talent-assets/img_2.png";
import Img3 from "assets/hire-talent-assets/img_3.png";
import Img4 from "assets/hire-talent-assets/img_4.png";
import Img5 from "assets/hire-talent-assets/img_5.png";
import Img6 from "assets/hire-talent-assets/img_6.png";
import Img7 from "assets/hire-talent-assets/img_7.png";
import Img8 from "assets/hire-talent-assets/img_8.png";
import Metalogo from "assets/hire-talent-assets/Meta-Logo.svg";
import MicrosoftLogo from "assets/hire-talent-assets/Microsoft-logo.svg";
import NextArrow from "assets/hire-talent-assets/navigation-arrow-right.svg";
import PrevArrow from "assets/hire-talent-assets/navigation-arrow-left.svg";
import ReviewProfile from "assets/hire-talent-assets/review-profile.png";
import ReviewProfile2 from "assets/hire-talent-assets/review_profile2.png";
import ReviewProfile3 from "assets/hire-talent-assets/review_profile3.png";
import TechTalentIllustration from "assets/hire-talent-assets/bg-image-2812.png";
import TwitterLogo from "assets/hire-talent-assets/twitter-logo.svg";
import UserSearchIcon from "assets/hire-talent-assets/user-search.svg";
import VideoCallIcon from "assets/hire-talent-assets/video-call.svg";

const HireTalent: NextPage = () => {
  return (
    <div className={styles.hireTalent}>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GeneralLayout>
        <section className={styles.section1}>
          <div className={styles.bgContainer}>
            <div className={styles.floatingImage1}>
              <Image src={Img5} alt="" />
            </div>
            <div className={styles.floatingImage2}>
              <Image src={Img4} alt="" />
            </div>
            <div className={styles.floatingImage3}>
              <Image src={Img6} alt="" />
            </div>
            <div className={styles.floatingImage4}>
              <Image src={Img8} alt="" />
            </div>
            <Image src={TechTalentIllustration} alt="" />
          </div>
          <article className={styles.section1Container}>
            <div className={styles.section1Content}>
              <h1>
                Find, Attract and Hire African Tech Talents
                <span>🌍</span>
              </h1>
              <p>
                Get matched with remote-ready African talents from Africa&apos;s
                #1 remote work community🌍.
              </p>
            </div>

            <form>
              <div className={styles.inputForm}>
                <div className={styles.iconContainer}>
                  <Image src={EmailIcon} alt="" />
                </div>
                <input
                  type="email"
                  name="email"
                  id="email"
                  className={styles.emailInput}
                  placeholder="Email"
                />
              </div>
              <button className={styles.emailBtn}>Join Now</button>
            </form>
          </article>
        </section>
        <section className={styles.section2}>
          <article className={styles.section2Container}>
            <div className={styles.bookIllustrator}>
              <div className={styles.floatingImg1}>
                <Image src={Img2} alt="" />
              </div>
              <div className={styles.floatingImg2}>
                <Image src={Img1} alt="" />
              </div>
              <div className={styles.floatingImg3}>
                <Image src={Img3} alt="" />
              </div>
              <div className={styles.floatingImg4}>
                <Image src={Img7} alt="" />
              </div>
              <Image src={BookIllustrator} alt="" />
            </div>
            <div className={styles.bookContent}>
              <div className={styles.content}>
                <div className={styles.contentTitle}>
                  <h3>
                    Get the best candidate profiles straight to your inbox
                  </h3>
                </div>
                <div className={styles.contentList}>
                  <p>
                    Connect with skilled African talents for full-time or
                    project-based employment.
                  </p>
                  <p>
                    Fill your direct sourcing pipeline with ready-to-work
                    candidates to reduce time-to-hire by 55%
                  </p>
                  <p>
                    Increase the quality of your hires by matching with skills,
                    experience, and personality traits pre-screening.
                  </p>
                </div>
              </div>
              <button className={styles.bookBtn}>
                <Image src={CallIcon} alt="" />
                <span className={styles.bookbtncontent}>Book a call now</span>
              </button>
            </div>
          </article>
        </section>
        <section className={styles.section3}>
          <div className={styles.section3Container}>
            <h3>
              Hire directly from a pool of remote-ready tech talents all over
              Africa.
            </h3>
            <div className={styles.buttonContainer}>
              <button className={styles.viewTalentBtn}>
                <p>View Talent Directory</p>
              </button>
              <button className={styles.requestTalentBtn}>
                <p>Request Talent Match</p>
              </button>
            </div>
          </div>
        </section>
        <section className={styles.infoSection}>
          <h3>Get matched with the best talents</h3>
          <div className={styles.cardContainer}>
            <article className={styles.card}>
              <Image src={UserSearchIcon} alt="" />
              <div>
                <h3>View Talents</h3>
                <p>
                  Click <strong>View Talent Directory</strong> above to explore
                  our talent database
                </p>
              </div>
            </article>
            <article className={styles.card}>
              <Image src={VideoCallIcon} alt="" />
              <div>
                <h3>Schedule call</h3>
                <p>
                  Tell us the skills and experience you’re looking for in
                  addition to the salary, plus any other matters related to your
                  ideal talent.
                </p>
              </div>
            </article>
            <article className={styles.card}>
              <Image src={HandShakeIcon} alt="" />
              <div>
                <h3>Get matched</h3>
                <p>
                  Our AI-powered platform will evaluate your preference against
                  the candidates to match you with the right fit
                </p>
              </div>
            </article>
          </div>
          <div className={styles.CallToActionSection}>
            <button className={styles.CallToActionBtn}>
              <p>Talk to us</p> <Image src={ArrowLeft} alt="" />
            </button>
          </div>
        </section>
        <section className={styles.reviewSection}>
          <h3>
            What remote-first companies say about the AfriSplash Remotely
            community
          </h3>
          <div className={styles.reviewContainer}>
            <Image src={PrevArrow} alt="" />
            <article>
              <p>
                “Afrisplash Remotely is a great community, the team is super
                fantastic and helped me to find the best talent matching our
                expectations. We would love to keep engaging with the team and
                contribute as much as we can to grow this community.”
              </p>
              <div className={styles.profile}>
                <Image src={ReviewProfile} alt="" />
                <div className={styles.profileDetails}>
                  <p>Princess Gabriel</p>
                  <p>Founder @ Rootlo</p>
                </div>
              </div>
            </article>
            <article className={styles.centerArticle}>
              <div className={styles.blockQuote}>
                <div className={styles.blockQuoteContainer}>
                  <Image src={BlockQuote} alt="" />
                </div>
              </div>
              <p>
                “Afrisplash Remotely is a great community, the team is super
                fantastic and helped me to find the best talent matching our
                expectations. We would love to keep engaging with the team and
                contribute as much as we can to grow this community.”
              </p>
              <div className={styles.profile}>
                <Image src={ReviewProfile2} alt="" />
                <div className={styles.profileDetails}>
                  <p>Ujjwal Singh</p>
                  <p>Founder @ Haulify</p>
                </div>
              </div>
            </article>
            <article className={styles.lastArticle}>
              <p>
                “Afrisplash Remotely is a great community, the team is super
                fantastic and helped me to find the best talent matching our
                expectations. We would love to keep engaging with the team and
                contribute as much as we can to grow this community.”
              </p>
              <div className={styles.profile}>
                <Image src={ReviewProfile3} alt="" />
                <div className={styles.profileDetails}>
                  <p>Lucy Brian Anish</p>
                  <p>Founder @ Anisha Groups</p>
                </div>
              </div>
            </article>
            <Image src={NextArrow} alt="" />
          </div>
        </section>
        <section className={styles.industrySection}>
          <h3>
            Work with talents who learn how to do remote work from industry
            leaders
          </h3>
          <div className={styles.industryImgContainer}>
            <Image src={MicrosoftLogo} alt="" />
            <div className={styles.industryImg}>
              <Image src={TwitterLogo} alt="" />
            </div>
            <Image src={Metalogo} alt="" />
            <div className={styles.industryImg}>
              <Image src={AppleLogo} alt="" />
            </div>
            <Image src={GoogleLogo} alt="" />
          </div>
        </section>
        <section className={styles.remarkSections}>
          <div className={styles.remarkContainer}>
            <div className={styles.remarks}>
              <Image src={CheckBox} alt="" />
              <p>
                More remote talents within the community have access to global
                remote leaders.
              </p>
            </div>
            <div className={styles.remarks}>
              <Image src={CheckBox} alt="" />
              <p>
                We don&apos;t just offer you the top 1% of talent. We offer you
                grit, skill, creativity and the right fit.
              </p>
            </div>
            <div className={styles.remarks}>
              <Image src={CheckBox} alt="" />
              <p>
                We build on mutual trust to promote the remote working culture.
              </p>
            </div>
          </div>
        </section>
      </GeneralLayout>
    </div>
  );
};

export default HireTalent;
