version: "3.8"

services:
  app:
    container_name: "afri-frontend"
    image: "afri-frontend"
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

