export const jobIndustry = [
  { value: "Software Development", label: "Software Development" },
  { value: "Web Development", label: "Web Development" },
  { value: "Mobile App Development", label: "Mobile App Development" },
  { value: "Cloud Computing", label: "Cloud Computing" },
  { value: "Artificial Intelligence (AI) and Machine Learning", label: "Artificial Intelligence (AI) and Machine Learning" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Data Analytics and Business Intelligence", label: "Data Analytics and Business Intelligence" },
  { value: "Internet of Things (IoT)", label: "Internet of Things (IoT)" },
  { value: "DevOps (Development and Operations)", label: "DevOps (Development and Operations)" },
  { value: "Blockchain Technology", label: "Blockchain Technology" },
  { value: "Virtual Reality (VR) and Augmented Reality (AR)", label: "Virtual Reality (VR) and Augmented Reality (AR)" },
  { value: "Network Infrastructure", label: "Network Infrastructure" },
  { value: "Database Management", label: "Database Management" },
  { value: "Enterprise Resource Planning (ERP) Systems", label: "Enterprise Resource Planning (ERP) Systems" },
  { value: "Customer Relationship Management (CRM) Systems", label: "Customer Relationship Management (CRM) Systems" },
  { value: "E-commerce Platforms", label: "E-commerce Platforms" },
  { value: "Content Management Systems (CMS)", label: "Content Management Systems (CMS)" },
  { value: "Human Resources Information Systems (HRIS)", label: "Human Resources Information Systems (HRIS)" },
  { value: "Financial Technology (Fintech)", label: "Financial Technology (Fintech)" },
  { value: "Health Information Technology (HealthTech)", label: "Health Information Technology (HealthTech)" },
  { value: "Education Technology (EdTech)", label: "Education Technology (EdTech)" },
  { value: "Gaming Technology", label: "Gaming Technology" },
  { value: "Embedded Systems", label: "Embedded Systems" },
  { value: "Robotics", label: "Robotics" },
  { value: "Software Testing and Quality Assurance", label: "Software Testing and Quality Assurance" },
  { value: "Property Technology", label: "Property Technology" },
  { value: "AgriTech", label: "AgriTech" },
  { value: "Insurance Technology", label: "Insurance Technology" },
  { value: "LegalTech", label: "LegalTech" },
  { value: "Marketing Technology", label: "Marketing Technology" },


]

export const expLevel = [
  { value: "Intermediate", label: "Intermediate" },
  { value: "Beginner", label: "Beginner" },
  { value: "Senior", label: "Senior" },
  { value: "Junior", label: "Junior" },
  { value: "All", label: "All" },

  ]

export const jobsType = [
  { value: "Hybrid", label: "Hybrid" },
  { value: "Remote", label: "Remote" }

]

export const Location = [
  { label: "Afghanistan", value: "Afghanistan" },
  { label: "Albania", value: "Albania" },
  { label: "Algeria", value: "Algeria" },
  { label: "Andorra", value: "Andorra" },
  { label: "Angola", value: "Angola" },
  { label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { label: "Argentina", value: "Argentina" },
  { label: "Armenia", value: "Armenia" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Azerbaijan", value: "Azerbaijan" },
  { label: "Bahamas", value: "Bahamas" },
  { label: "Bahrain", value: "Bahrain" },
  { label: "Bangladesh", value: "Bangladesh" },
  { label: "Barbados", value: "Barbados" },
  { label: "Belarus", value: "Belarus" },
  { label: "Belgium", value: "Belgium" },
  { label: "Belize", value: "Belize" },
  { label: "Benin", value: "Benin" },
  { label: "Bhutan", value: "Bhutan" },
  { label: "Bolivia", value: "Bolivia" },
  { label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { label: "Botswana", value: "Botswana" },
  { label: "Brazil", value: "Brazil" },
  { label: "Brunei", value: "Brunei" },
  { label: "Bulgaria", value: "Bulgaria" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Burundi", value: "Burundi" },
  { label: "Cabo Verde", value: "Cabo Verde" },
  { label: "Cambodia", value: "Cambodia" },
  { label: "Cameroon", value: "Cameroon" },
  { label: "Canada", value: "Canada" },
  { label: "Central African Republic", value: "Central African Republic" },
  { label: "Chad", value: "Chad" },
  { label: "Chile", value: "Chile" },
  { label: "China", value: "China" },
  { label: "Colombia", value: "Colombia" },
  { label: "Comoros", value: "Comoros" },
  { label: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
  { label: "Costa Rica", value: "Costa Rica" },
  { label: "Croatia", value: "Croatia" },
  { label: "Cuba", value: "Cuba" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Czechia (Czech Republic)", value: "Czechia (Czech Republic)" },
  { label: "Democratic Republic of the Congo", value: "Democratic Republic of the Congo" },
  { label: "Denmark", value: "Denmark" },
  { label: "Djibouti", value: "Djibouti" },
  { label: "Dominica", value: "Dominica" },
  { label: "Dominican Republic", value: "Dominican Republic" },
  { label: "Ecuador", value: "Ecuador" },
  { label: "Egypt", value: "Egypt" },
  { label: "El Salvador", value: "El Salvador" },
  { label: "Equatorial Guinea", value: "Equatorial Guinea" },
  { label: "Eritrea", value: "Eritrea" },
  { label: "Estonia", value: "Estonia" },
  { label: "Eswatini (fmr. Swaziland)", value: "Eswatini (fmr. Swaziland)" },
  { label: "Ethiopia", value: "Ethiopia" },
  { label: "Fiji", value: "Fiji" },
  { label: "Finland", value: "Finland" },
  { label: "France", value: "France" },
  { label: "Gabon", value: "Gabon" },
  { label: "Gambia", value: "Gambia" },
  { label: "Georgia", value: "Georgia" },
  { label: "Germany", value: "Germany" },
  { label: "Ghana", value: "Ghana" },
  { label: "Greece", value: "Greece" },
  { label: "Grenada", value: "Grenada" },
  { label: "Guatemala", value: "Guatemala" },
  { label: "Guinea", value: "Guinea" },
  { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "Guyana", value: "Guyana" },
  { label: "Haiti", value: "Haiti" },
  { label: "Holy See", value: "Holy See" },
  { label: "Honduras", value: "Honduras" },
  { label: "Hungary", value: "Hungary" },
  { label: "Iceland", value: "Iceland" },
  { label: "India", value: "India" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Iran", value: "Iran" },
  { label: "Iraq", value: "Iraq" },
  { label: "Ireland", value: "Ireland" },
  { label: "Israel", value: "Israel" },
  { label: "Italy", value: "Italy" },
  { label: "Ivory Coast", value: "Ivory Coast" },
  { label: "Jamaica", value: "Jamaica" },
  { label: "Japan", value: "Japan" },
  { label: "Jordan", value: "Jordan" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Kenya", value: "Kenya" },
  { label: "Kiribati", value: "Kiribati" },
  { label: "Kuwait", value: "Kuwait" },
  { label: "Kyrgyzstan", value: "Kyrgyzstan" },
  { label: "Nigeria", value: "Nigeria" }
]

export const gender = [
    { value: "female", label: "Female" },
    { value: "male", label: "Male" },
    { value: "any", label: "Any" }
  ]

export const currency = [
  {value:'USD', label:"USD"},
  {value:"NGN", label:"NGN"},
  {value:'EUR', label:'EUR'}
]

export const payment = [
    { value: "daily", label: "Daily" },
    { value: "monthly", label: "Monthly" },
    { value: "yearly", label: "Yearly" }
  ]