blank_issues_enabled: false
contact_links:
  - name: AfriSplash Community
    url: https://join.slack.com/t/afrisplash/shared_invite/zt-xifsxpw3-7f23alnl7mhtaw5vmjF6vw
    about:  Report issues on the AfriSplash Community