import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "styles/Login.module.scss";
import africanwomansmiling from "assets/africanwomansmiling.png";
import logo from "assets/logo.png";
import person1 from "assets/person1.png";
import person2 from "assets/person2.png";
import google from "assets/svg/google.svg";

const Login: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-6">
        <div className="col-span-3">
          <nav className={styles.nav}>
            <Image src={logo} alt="logo.png" />
            <p className="ml-4 font-[600]">AfriSplashRemotely</p>
          </nav>
          <div className={styles.span}>
            <h2 className={styles.h2}>Welcome Back</h2>
            <p className="mb-20">Log in to see what&apos;s new</p>

            <button
              className={`flex justify-center items-center ${styles.button}`}
            >
              <span className="mr-2">
                {" "}
                <Image src={google} alt="google icon" />
              </span>{" "}
              Log in with Google
            </button>

            <div className="flex flex-row items-center my-6 mx-auto">
              <hr className="w-[100px] mr-5 h-[5px] text-[#D9DEDC]" />
              or with email
              <hr className="ml-5 w-[100px] h-[5px] text-[#97a39e]" />
            </div>

            <input
              className={styles.input}
              type="email"
              placeholder="email@gmail.com"
            />
            <input
              className={styles.input}
              type="password"
              placeholder="Password"
            />
            <div className="flex justify-between mb-4">
              <div className="flex">
                <input type="checkbox" />
                <p className="ml-2">Keep me logged in</p>
              </div>
              <Link href={"/reset-pasword"}>
                <p>Forgot Password?</p>
              </Link>
            </div>
            <button className={`bg-[#1C1D36] text-white ${styles.button}`}>
              Log in
            </button>
            <p className="text-center mt-4">
              Don&apos;t have an account?{" "}
              <span className="text-[#0D5520] underline font-[700]">
                <Link href={"/auth/signup"}>Join now</Link>{" "}
              </span>
            </p>
          </div>
        </div>
        <div className={`${styles.span2} relative col-span-3 bg-[#FDF1C9]`}>
          <div
            className={`${styles.bg}  pt-10 mt-14 px-8 w-[80%] rounded-[24px] mx-auto`}
          >
            <div
              className="absolute rounded-[24px] bg-white py-4 px-6 top-48 right-14"
              style={{
                boxShadow: "4px 4px 16px rgba(0, 0, 0, 0.1)",
              }}
            >
              <Image src={person2} alt="africanwomansmiling.png" />
            </div>
            <p className="text-[32px] font-[600]">
              Go global- join the community to get top remote jobs from truly
              inclusive companies
            </p>
            <div
              className="absolute rounded-[24px] bg-white py-4 px-6 bottom-60 left-14"
              style={{
                boxShadow: "4px 4px 16px rgba(0, 0, 0, 0.1)",
              }}
            >
              <Image src={person1} alt="africanwomansmiling.png" />
            </div>
            <span className="">
              <Image
                layout="responsive"
                src={africanwomansmiling}
                alt="africanwomansmiling.png"
              />
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
