import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "styles/Login.module.scss";
import africanwomansmiling from "assets/africanwomansmiling.png";
import logo from "assets/logo.png";
import person1 from "assets/person1.png";
import person2 from "assets/person2.png";
import google from "assets/svg/google.svg";
import { useForm } from "react-hook-form";
import axios from "axios";

const Login: NextPage = () => {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  const onSubmit = (data: any) => {
    console.log(data);
    axios
      .post("https://api.afrisplash.com/api/v1/auth/login", data)
      .then((res) => {
        console.log(res);
        return res;
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex ">
        <div className="w-6/12">
          <div className="w-9/12 mx-auto">
            <nav className={styles.nav}>
              <Image
                src="/admin_logo.svg"
                alt="afrisplash"
                width={150}
                height={150}
              />
            </nav>
            <div className={`mt-10 ${styles.span}`}>
              <h2 className={styles.h2}>Welcome Back</h2>
              <p className="mb-20">Log in to see what&apos;s new</p>

              <button
                className={`flex justify-center items-center ${styles.button}`}
              >
                <span className="mr-2">
                  <Image src={google} alt="google icon" />
                </span>
                Log in with Google
              </button>

              <div className="flex flex-row items-center my-6 mx-auto">
                <hr className="w-[100px] mr-5 h-[5px] text-[#D9DEDC]" />
                or with email
                <hr className="ml-5 w-[100px] h-[5px] text-[#97a39e]" />
              </div>
              <form className="w-full" onSubmit={handleSubmit(onSubmit)}>
                <div className="w-full ">
                  <input
                    className={styles.input}
                    type="email"
                    placeholder="email@gmail.com"
                    {...register("email", { required: "Email is required" })}
                  />
                  {errors.email && (
                    <p role="alert" className="error_message pl-2 py-2">
                      {" "}
                      {(errors.email as any).message}
                    </p>
                  )}
                </div>
                <div>
                  <input
                    className={styles.input}
                    type="password"
                    placeholder="Password"
                    {...register("password", {
                      required: "Password is required",
                    })}
                  />
                  {errors.password && (
                    <p role="alert" className="error_message pl-2 py-2">
                      {" "}
                      {(errors.password as any).message}
                    </p>
                  )}
                </div>
                <div className="flex justify-between mb-4">
                  <div className="flex">
                    <input type="checkbox" />
                    <p className="ml-2">Keep me logged in</p>
                  </div>
                  <Link href={"/reset-pasword"} legacyBehavior>
                    <p>Forgot Password?</p>
                  </Link>
                </div>
                <input
                  value="Log in"
                  type="submit"
                  className={`bg-dark_blue hover:bg-primary_green cursor-pointer text-white ${styles.button}`}
                />
              </form>
              <p className="text-center mt-4">
                Don&apos;t have an account?
                <span className="text-[#0D5520] underline font-[700]">
                  <Link href={"/auth/signup"}>Join now</Link>
                </span>
              </p>
            </div>
          </div>
        </div>
        <div className={`${styles.span2} relative w-6/12 bg-[#FDF1C9]`}>
          <div
            className={`${styles.bg}  pt-10 mt-14 px-8 w-[80%] rounded-[24px] mx-auto`}
          >
            <div
              className="absolute rounded-[24px] bg-white py-4 px-6 top-48 right-14"
              style={{
                boxShadow: "4px 4px 16px rgba(0, 0, 0, 0.1)",
              }}
            >
              <Image src={person2} alt="africanwomansmiling.png" />
            </div>
            <p className="text-[32px] font-[600]">
              Go global- join the community to get top remote jobs from truly
              inclusive companies
            </p>
            <div
              className="absolute rounded-[24px] bg-white py-4 px-6 bottom-60 left-14"
              style={{
                boxShadow: "4px 4px 16px rgba(0, 0, 0, 0.1)",
              }}
            >
              <Image src={person1} alt="africanwomansmiling.png" />
            </div>
            <span className="">
              <Image src={africanwomansmiling} alt="africanwomansmiling.png" />
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
