import type { NextPage } from "next";
import Head from "next/head";
import GeneralLayout from "@/layouts/generalLayout";
import { AdjustmentsHorizontalIcon } from "@heroicons/react/24/solid";
import SearchTwo from "@/components/atoms/SearchTwo/SearchTwo";
import { CandidateSideBar } from "@/components/Candidates";
import Image from "next/image";
import sms from 'assets/sms.png';
import { MentorCard } from "@/components/Forum/MentorCardComponent";
import { mentorsData } from "@/utils";
import Button from "@/components/atoms/Button/Button";

const Candidates: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Afrisplash</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GeneralLayout>
                <div className="afri-container">
                    <div className="mt-8 py-4 " >
                        <div className="flex flex-row gap-4 items-center">
                            <div>
                                <AdjustmentsHorizontalIcon className="w-6 h-6" />
                            </div>
                            <div>
                                <SearchTwo placeholder="Search candidates" />
                            </div>
                            <div>
                                <p className="font-medium">Showing 1-10 of <span className="font-bold text-primary_green">48 Canditates</span></p>
                            </div>
                        </div>
                    </div>

                </div>
                <div className="mt-8 w-11/12 mx-auto py-8">
                    <div className="grid grid-cols-3 gap-6">
                        <div className="mt-4">
                            <CandidateSideBar />
                        </div>
                        <div className="col-span-2">
                            <div className="flex justify-between">
                                <button className="flex gap-2 bg-[#0D5520] items-center justify-center  p-4 rounded-md hover:opacity-80">
                                    <span className="text-white font-medium">Get talent profiles</span>
                                    <Image src={sms} alt="sms" />
                                </button>
                                <div className="flex flex-row justify-center items-center">
                                    <p className="font-meduim">Sort by: </p>
                                    <div className="mx-2">
                                        <SearchTwo placeholder="Newest" />
                                    </div>
                                </div>
                            </div>
                            <div className="mt-8">
                                <div className="grid gap-6 lg:grid-cols-3">
                                    {mentorsData.map((mentor) => (
                                        <MentorCard
                                            key={mentor.id}
                                            name={mentor.name}
                                            position={mentor.position}
                                            role={mentor.role}
                                            flag={mentor.flag}
                                            src={mentor.src}
                                        />
                                    ))}
                                </div>
                                <div className='mt-12  flex justify-center'>
                                    <Button
                                        type='filled'
                                        color='white'
                                        text='Load more candidates'
                                        classes="w-64 h-12 rounded-md text-sm font-medium capitalize  text-white bg-dark_blue hover:opacity-80"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </GeneralLayout>
        </div>

    )
}


export default Candidates