import type { NextPage } from "next";
import Head from "next/head";
import GeneralLayout from 'layouts/generalLayout';


const Employer: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Afrisplash</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GeneralLayout>
                <div>
                    <div></div>
                </div>
            </GeneralLayout>

        </div>
    )
}


export default Employer