import type { NextPage } from "next";
import Head from "next/head";
import GeneralLayout from "../layouts/generalLayout";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <GeneralLayout>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </GeneralLayout>
  );
};

export default Home;
