import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "components/molecules/Header/Header";
import GeneralLayout from "layouts/generalLayout";
import styles from "styles/Home.module.scss";
import chipper from "assets/icons/chipper.svg";
import haulify from "assets/icons/haulify.svg";
import nextford from "assets/icons/nextford.svg";
import panther from "assets/icons/panther.svg";
import rootlo from "assets/icons/rootlo.svg";
import scopic from "assets/icons/scopic.svg";
import { jobCat, jobData, talentDets, toArrayOfObjects } from "utils/fakeData";
import JobCard from "components/jobCard";
import JobCategory from "components/molecules/jobCategory";
import TalentSummary from "components/molecules/TalentSummary";
import { motion, useAnimation } from "framer-motion";
import { useEffect } from "react";

const HomeJobs = () => {
  const homeJobData = toArrayOfObjects(jobData[0], 5);
  const homeJobCat = toArrayOfObjects(jobCat, 9);
  return (
    <section className={`w-full ${styles.job_wrapper}`}>
      <div className="py-28 space-y-24 w-11/12 xl:w-10/12 mx-auto">
        <section className="space-y-10">
          <div className="text-center space-y-5">
            <h2 className="text-4xl font-semibold">Popular job categories</h2>
            <p className="text-gray-500">224 live | 49 added today</p>
          </div>
          <div className="w-full flex flex-wrap justify-between ">
            {homeJobCat.map((data: any, index: number) => (
              <JobCategory key={index} data={data} />
            ))}
          </div>
        </section>
        <section className="space-y-16 ">
          <div className="text-center space-y-8">
            <h2 className="text-4xl font-semibold">Featured jobs</h2>
            <div className="text-gray-500">
              <p>Your dream remote job is an application away.</p>
              <p>
                Start applying to accessible opportunities that allows you live,
                work and succeed from anywhere.
              </p>
            </div>
          </div>
          <div className="w-full">
            {homeJobData.map(
              (data, index): JSX.Element => (
                <div key={index}>
                  <JobCard
                    image={data.image}
                    alt={"company image"}
                    company={data.company}
                    service={data.service}
                    employees={data.employees}
                    offer={data.offer}
                    priceRange={data.priceRange}
                    postDate={data.postDate}
                    hiring={data.hiring}
                    promoted={data.promoted}
                  />
                </div>
              )
            )}
          </div>
        </section>
      </div>
    </section>
  );
};

const Talents = () => {
  const homeTalents = toArrayOfObjects(talentDets, 12);

  return (
    <section className="w-full ">
      <div className="py-28 space-y-24 w-11/12 xl:w-10/12 mx-auto">
        <section>
          <div className="text-center space-y-5">
            <h3 className="capitalize font-semibold text-4xl">
              our top talents
            </h3>
            <div className="text-gray-500 flex justify-center">
              <p className="w-5/12">
                Browse through the talent pool from our community and partners.
                Find tech and non-tech talents in weeks, not months.
              </p>
            </div>
          </div>
          <div className="w-full flex flex-wrap justify-between ">
            {homeTalents.flatMap((item: any, index: number) => (
              <TalentSummary key={index} data={item} />
            ))}
          </div>
        </section>
      </div>
    </section>
  );
};

const Home: NextPage = () => {
  const globalCompanies = [chipper, nextford, haulify, panther, rootlo, scopic];

  const boxVariant = {
    visible: { opacity: 1, scale: 1, transition: { duration: 1 } },
    hidden: { opacity: 0, scale: 0 },
  };
  
  return (
    <GeneralLayout>
      <Head>
        <title>Afrisplash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
      
      <section className="w-full my-10 mt-32">
        <div className="w-10/12 mx-auto space-y-10">
          <h3 className="text-center text-gray-400 text-2xl font-light">
            Trusted by these global companies
          </h3>
          <div className="flex justify-between ">
            {globalCompanies.map((item: any, index: number) => (
              <Image key={index} src={item} alt="global companies" />
            ))}
          </div>
        </div>
      </section>
      <HomeJobs />
      <Talents />
    </GeneralLayout>
  );
};

export default Home;
