name: Test Actions

on:
  pull_request:
    branches: ['main']

jobs:
  echo-out:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo name
        run: echo "Hello world"
